"""IFC ingest: units, north, georeferencing and window-to-space containment.

Milestone M2's acceptance criterion is that the fixture loads with correct
north, units and containment, so those three get the most attention here.

The fixture is generated by ``tests/fixtures/make_sample_building.py`` and is
deliberately awkward: millimetre units, true north 30 degrees off project
north, and one window with no space boundary.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import ifcopenshell
import numpy as np
import pytest

from sun_study.core.orientation import SiteOrientation
from sun_study.ingest.ifc import GeoreferencingError, read_ifc
from sun_study.ingest.scene import SceneConfig, build_scene, planar_face_grid

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"
SAMPLE = FIXTURES / "sample_building.ifc"

# Values the fixture generator declares. If these drift apart the fixture has
# been regenerated with different inputs and the golden results are stale.
EXPECTED_LATITUDE = -33.75
EXPECTED_LONGITUDE = 151.25
EXPECTED_ELEVATION_M = 20.0
EXPECTED_NORTH_BEARING = 30.0
EXPECTED_UNIT_SCALE = 0.001


@pytest.fixture(scope="module")
def model() -> Any:
    return read_ifc(SAMPLE)


def test_fixture_is_committed() -> None:
    """The fixture is synthetic and committed on purpose (brief section 10)."""
    assert SAMPLE.is_file(), (
        f"{SAMPLE} is missing; regenerate with "
        f"'uv run python tests/fixtures/make_sample_building.py'"
    )


def test_committed_fixture_matches_its_generator(tmp_path: Path) -> None:
    """The .ifc must be exactly what the script produces, byte for byte.

    Catches two things that would otherwise be invisible: the committed file
    having been hand-edited, and the generator having changed without the
    fixture and its golden results being regenerated.

    This is only possible because generation is deterministic -- GUIDs come
    from a counter and the SPF header timestamp is pinned, since IfcOpenShell
    otherwise stamps the current time and every regeneration would be a diff.
    """
    import subprocess
    import sys

    script = FIXTURES / "make_sample_building.py"
    regenerated = tmp_path / "sample_building.ifc"

    source = script.read_text(encoding="utf-8").replace(
        'destination = Path(__file__).parent / "sample_building.ifc"',
        f"destination = Path({str(regenerated)!r})",
    )
    relocated = tmp_path / "generator.py"
    relocated.write_text(source, encoding="utf-8")

    subprocess.run([sys.executable, str(relocated)], check=True, capture_output=True)

    assert regenerated.read_bytes() == SAMPLE.read_bytes(), (
        "the committed fixture differs from what its generator produces; "
        "re-run 'uv run python tests/fixtures/make_sample_building.py' and "
        "regenerate the golden file with SUN_STUDY_UPDATE_GOLDEN=1"
    )


# ---------------------------------------------------------------------------
# Units -- the two scales that must not be conflated.
# ---------------------------------------------------------------------------
def test_declared_unit_is_millimetres(model: Any) -> None:
    assert model.length_unit_scale == pytest.approx(EXPECTED_UNIT_SCALE)


def test_geometry_arrives_in_metres_not_project_units(model: Any) -> None:
    """The iterator already applies the unit scale; applying it again would
    shrink a 2.4 m window to 2.4 mm."""
    windows = model.of_class("IfcWindow")
    assert len(windows) == 4

    lower, upper = windows[0].bounds
    width = float(np.max(upper - lower))
    assert width == pytest.approx(2.4, abs=1e-6), (
        f"window measures {width} across; expected 2.4 m. A value near 2400 means "
        f"the geometry is still in millimetres, and one near 0.0024 means the unit "
        f"scale has been applied twice."
    )


def test_building_extent_is_plausible_in_metres(model: Any) -> None:
    mesh = model.occluder_mesh()
    extent = mesh.vertices.max(axis=0) - mesh.vertices.min(axis=0)
    assert 20.0 < float(extent[0]) < 100.0, f"building spans {extent[0]} m across"
    assert 5.0 < float(extent[2]) < 30.0, f"building is {extent[2]} m tall"


def test_site_elevation_is_converted_from_project_units(model: Any) -> None:
    """RefElevation is an attribute, so unlike geometry it *does* need scaling.

    The fixture stores 20000 (millimetres). Reading it unscaled would place the
    site 20 km up; scaling geometry as well would put it at 20 mm.
    """
    assert model.site_elevation_m == pytest.approx(EXPECTED_ELEVATION_M)


# ---------------------------------------------------------------------------
# North and georeferencing.
# ---------------------------------------------------------------------------
def test_true_north_bearing_is_read(model: Any) -> None:
    assert model.true_north_bearing_deg == pytest.approx(EXPECTED_NORTH_BEARING, abs=1e-9)


def test_geolocation_is_read(model: Any) -> None:
    assert model.latitude_deg == pytest.approx(EXPECTED_LATITUDE)
    assert model.longitude_deg == pytest.approx(EXPECTED_LONGITUDE)


def test_orientation_requires_an_explicit_timezone(model: Any) -> None:
    """Decision D3. IFC has no IANA zone, and none is invented."""
    orientation = model.orientation("Australia/Sydney")
    assert isinstance(orientation, SiteOrientation)
    assert orientation.timezone == "Australia/Sydney"

    with pytest.raises(ValueError, match="timezone"):
        model.orientation("")


def test_describe_echoes_what_a_human_must_check(model: Any) -> None:
    line = model.describe("Australia/Sydney")
    assert "33.750000S" in line
    assert "151.250000E" in line
    assert "30.000" in line
    assert "Australia/Sydney" in line
    assert "0.001" in line


# ---------------------------------------------------------------------------
# Failing loudly. Every one of these silently rotates or relocates results.
# ---------------------------------------------------------------------------
def _strip_and_write(destination: Path, mutate: Any) -> Path:
    file = ifcopenshell.open(str(SAMPLE))
    mutate(file)
    file.write(str(destination))
    return destination


def test_missing_true_north_raises(tmp_path: Path) -> None:
    def remove_north(file: Any) -> None:
        for context in file.by_type("IfcGeometricRepresentationContext", include_subtypes=False):
            context.TrueNorth = None

    path = _strip_and_write(tmp_path / "no_north.ifc", remove_north)
    with pytest.raises(GeoreferencingError, match="North Direction"):
        read_ifc(path)


def test_missing_latitude_raises(tmp_path: Path) -> None:
    def remove_location(file: Any) -> None:
        for site in file.by_type("IfcSite"):
            site.RefLatitude = None
            site.RefLongitude = None

    path = _strip_and_write(tmp_path / "no_location.ifc", remove_location)
    with pytest.raises(GeoreferencingError, match="Project Location"):
        read_ifc(path)


def test_ambiguous_multiple_located_sites_raises(tmp_path: Path) -> None:
    """Two georeferenced sites means the tool cannot know which one governs."""

    def duplicate_site(file: Any) -> None:
        original = file.by_type("IfcSite")[0]
        file.create_entity(
            "IfcSite",
            GlobalId=ifcopenshell.guid.new(),
            Name="Second Site",
            RefLatitude=original.RefLatitude,
            RefLongitude=original.RefLongitude,
            RefElevation=original.RefElevation,
        )

    path = _strip_and_write(tmp_path / "two_sites.ifc", duplicate_site)
    with pytest.raises(GeoreferencingError, match="ambiguous"):
        read_ifc(path)


def test_missing_file_raises() -> None:
    with pytest.raises(FileNotFoundError):
        read_ifc(FIXTURES / "does_not_exist.ifc")


def test_ifcopenshell_helper_would_have_defaulted_silently() -> None:
    """Why this module does not use ``get_true_north`` for the presence check.

    The helper returns 0 for a file with no TrueNorth, which is indistinguishable
    from a project genuinely aligned to true north. That is the silent default
    the brief forbids, so this pins the behaviour we are deliberately avoiding.
    """
    import ifcopenshell.util.geolocation

    file = ifcopenshell.open(str(SAMPLE))
    for context in file.by_type("IfcGeometricRepresentationContext", include_subtypes=False):
        context.TrueNorth = None

    assert ifcopenshell.util.geolocation.get_true_north(file) == 0


# ---------------------------------------------------------------------------
# Containment -- which space does each window serve.
# ---------------------------------------------------------------------------
@pytest.fixture(scope="module")
def scene(model: Any) -> Any:
    return build_scene(model, SceneConfig(timezone="Australia/Sydney"))


def test_every_window_resolves_to_the_right_apartment(scene: Any) -> None:
    resolved = {a.window_name: a.space_name for a in scene.assignments}
    assert resolved == {
        "Window L00-A": "Apartment L00-A",
        "Window L00-B": "Apartment L00-B",
        "Window L01-A": "Apartment L01-A",
        "Window L01-B": "Apartment L01-B",
    }


def test_both_resolution_routes_are_exercised_and_reported(scene: Any) -> None:
    """The fixture omits one space boundary precisely to reach the fallback."""
    methods = {a.window_name: a.method for a in scene.assignments}
    assert methods["Window L00-A"] == "geometric"
    assert methods["Window L00-B"] == "space-boundary"

    assert scene.provenance["resolved_by_space_boundary"] == 3
    assert scene.provenance["resolved_geometrically"] == 1
    assert scene.provenance["unresolved"] == 0


def test_a_window_far_from_any_space_is_left_unresolved(model: Any) -> None:
    """Guessing would attach a stairwell window to whichever room is nearest."""
    from sun_study.ingest.scene import _assign_windows

    windows = model.of_class("IfcWindow")
    assignments = _assign_windows(model, windows, ())
    assert all(a.method == "unresolved" for a in assignments)
    assert all(a.space_id is None for a in assignments)


def test_living_rooms_are_matched_on_long_name(model: Any) -> None:
    """Archicad puts the Zone category in LongName and the apartment id in Name.

    Matching only Name finds nothing, which reads as a building with no living
    rooms rather than as a configuration error. See decision D6.
    """
    spaces = model.of_class("IfcSpace")
    assert all(space.long_name == "Living Room" for space in spaces)
    assert all(space.name.startswith("Apartment") for space in spaces)

    scene = build_scene(model, SceneConfig(timezone="Australia/Sydney"))
    assert scene.provenance["living_rooms_matched"] == 4
    assert scene.provenance["windows_assessed"] == 4


def test_a_non_matching_room_name_assesses_nothing(model: Any) -> None:
    """The failure mode above, made visible rather than silent."""
    scene = build_scene(
        model, SceneConfig(timezone="Australia/Sydney", living_room_space_names=("Kitchen",))
    )
    assert scene.provenance["living_rooms_matched"] == 0
    assert scene.provenance["windows_assessed"] == 0
    assert len(scene.window_samples) == 0


def test_empty_room_filter_assesses_every_space(model: Any) -> None:
    scene = build_scene(model, SceneConfig(timezone="Australia/Sydney", living_room_space_names=()))
    assert scene.provenance["living_rooms_matched"] == 4


# ---------------------------------------------------------------------------
# Sampling on real IFC geometry.
# ---------------------------------------------------------------------------
def test_window_samples_face_outward_and_clear_the_facade(model: Any, scene: Any) -> None:
    """Samples must sit outside the wall, or the facade shades its own windows."""
    samples = scene.window_samples
    assert len(samples) > 0

    # Every window in the fixture faces project +Y.
    np.testing.assert_allclose(samples.normals[:, 1], 1.0, atol=1e-9)

    walls = model.of_class("IfcWall")
    facade_y = max(float(wall.bounds[1][1]) for wall in walls)
    assert float(samples.positions[:, 1].min()) > facade_y, (
        "window samples must lie outside the outermost wall face"
    )


def test_window_sample_count_matches_the_grid(scene: Any) -> None:
    """A 2.4 x 1.8 m window at 200 mm is 12 x 9 = 108 samples, four windows."""
    assert len(scene.window_samples) == 4 * 12 * 9


def test_open_space_samples_face_up_and_sit_above_the_slab(scene: Any) -> None:
    samples = scene.open_space_samples
    assert len(samples) > 0
    np.testing.assert_allclose(samples.normals, np.tile([0.0, 0.0, 1.0], (len(samples), 1)))


def test_planar_face_grid_follows_a_rotated_window() -> None:
    """The in-plane basis is derived from the face, not assumed axis-aligned."""
    from sun_study.core.geometry import box, rotation_about_z

    angle = 37.0
    mesh = box((-1.2, -0.1, 0.0), (1.2, 0.1, 1.8)).rotated_about_z(angle)

    # The panel's outward face is -Y before rotation, so the expected normal is
    # that axis carried through the same rotation. Deriving it from the matrix
    # rather than by hand keeps the test honest about the sign convention.
    expected_normal = rotation_about_z(angle) @ np.array([0.0, -1.0, 0.0])

    samples = planar_face_grid(mesh, "w", expected_normal, spacing_m=0.2, surface_offset_m=0.05)
    assert samples is not None
    # A 2.4 x 1.8 m panel at 200 mm spacing.
    assert len(samples) == 12 * 9

    np.testing.assert_allclose(
        samples.normals, np.tile(expected_normal, (len(samples), 1)), atol=1e-12
    )
    np.testing.assert_allclose(samples.normals[:, 2], 0.0, atol=1e-12)

    # And the samples stand off the rotated face by exactly the offset.
    face_centre = rotation_about_z(angle) @ np.array([0.0, -0.1, 0.9])
    assert float((samples.positions.mean(axis=0) - face_centre) @ expected_normal) == pytest.approx(
        0.05, abs=1e-9
    )


def test_planar_face_grid_picks_the_face_the_hint_points_at() -> None:
    """The two big faces of a window panel differ only in sign, so the hint
    decides which one is glazed-side-out. Getting it wrong puts every sample
    inside the room."""
    from sun_study.core.geometry import box

    mesh = box((-1.2, -0.1, 0.0), (1.2, 0.1, 1.8))
    for hint in ([0.0, 1.0, 0.0], [0.0, -1.0, 0.0]):
        samples = planar_face_grid(mesh, "w", np.array(hint), spacing_m=0.4)
        assert samples is not None
        np.testing.assert_allclose(samples.normals[0], hint, atol=1e-12)


def test_planar_face_grid_returns_none_for_empty_geometry() -> None:
    from sun_study.core.geometry import TriangleMesh

    assert planar_face_grid(TriangleMesh.empty(), "w", np.array([0.0, 1.0, 0.0])) is None


def test_spaces_are_not_occluders(model: Any) -> None:
    """A Zone is a void; treating it as solid shades every apartment completely."""
    with_spaces = model.occluder_mesh(include_spaces=True).triangle_count
    without = model.occluder_mesh().triangle_count
    assert without < with_spaces
    assert without == sum(
        e.mesh.triangle_count for e in model.elements if e.ifc_class != "IfcSpace"
    )


def test_context_radius_drops_distant_occluders(model: Any) -> None:
    """D9. The cutoff is measured from the analysed spaces, not the file origin."""
    unlimited = build_scene(model, SceneConfig(timezone="Australia/Sydney"))
    clipped = build_scene(model, SceneConfig(timezone="Australia/Sydney", context_radius_m=15.0))
    assert clipped.occluders.triangle_count < unlimited.occluders.triangle_count


def test_provenance_records_the_assumptions(scene: Any) -> None:
    """A result separated from its assumptions cannot be reproduced or argued with."""
    for key in (
        "source",
        "schema",
        "length_unit_scale",
        "true_north_bearing_deg",
        "windows_assessed",
        "resolved_by_space_boundary",
        "resolved_geometrically",
        "unresolved",
        "vegetation_included",
    ):
        assert key in scene.provenance, f"provenance is missing {key}"

    assert scene.provenance["vegetation_included"] is False
    assert "vegetation excluded" in scene.config.describe()
    assert "context radius unlimited" in scene.config.describe()


# ---------------------------------------------------------------------------
# Golden results -- fail CI on drift (brief section 7).
# ---------------------------------------------------------------------------
GOLDEN = FIXTURES / "golden_sample_building.json"


def run_fixture_pipeline() -> dict[str, dict[str, float]]:
    """The whole chain on the fixture, reduced to per-apartment minutes."""
    import datetime as dt

    from sun_study.core.analysis import summarise_by_parent, sunlit_matrix
    from sun_study.core.occlusion import Occluder
    from sun_study.core.solar import assessment_times, solar_position

    model = read_ifc(SAMPLE)
    scene = build_scene(model, SceneConfig(timezone="Australia/Sydney"))

    times = assessment_times(
        dt.date(2024, 6, 21), "Australia/Sydney", dt.time(9, 0), dt.time(15, 0), 10
    )
    suns = scene.orientation.sun_vectors(
        solar_position(times, model.latitude_deg, model.longitude_deg)
    )
    occluder = Occluder(scene.occluders)
    names = {e.global_id: e.name for e in model.elements}

    results: dict[str, dict[str, float]] = {}
    for label, points in (
        ("living_room", scene.window_samples),
        ("open_space", scene.open_space_samples),
    ):
        summary = summarise_by_parent(points, sunlit_matrix(points, occluder, suns), 10.0)
        results[label] = {
            names.get(pid, pid): round(float(minutes), 3)
            for pid, minutes in zip(summary.parent_ids, summary.cumulative_minutes, strict=True)
        }
    return results


def test_fixture_results_match_the_golden_file() -> None:
    """Regenerate deliberately with SUN_STUDY_UPDATE_GOLDEN=1, never casually.

    A change here means the numbers this tool reports for a known building have
    moved. That is either a fix or a regression, and it should never pass
    unnoticed.
    """
    actual = run_fixture_pipeline()

    if os.environ.get("SUN_STUDY_UPDATE_GOLDEN") == "1":
        GOLDEN.write_text(json.dumps(actual, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    assert GOLDEN.is_file(), (
        f"{GOLDEN} is missing; create it with SUN_STUDY_UPDATE_GOLDEN=1 uv run pytest"
    )
    expected = json.loads(GOLDEN.read_text(encoding="utf-8"))

    assert actual.keys() == expected.keys()
    for section, values in expected.items():
        assert actual[section].keys() == values.keys(), f"{section} apartments changed"
        for name, minutes in values.items():
            assert actual[section][name] == pytest.approx(minutes, abs=1e-3), (
                f"{section} / {name}: {actual[section][name]} minutes, golden says {minutes}"
            )


def test_the_fixture_discriminates() -> None:
    """A golden file of four identical numbers would catch almost nothing.

    The fixture is built so the two storeys and the two sides all differ: the
    context block bites into the lower storey and the A side, and the balcony
    one level up overhangs each window. If these collapse together the fixture
    has stopped testing anything.
    """
    living = run_fixture_pipeline()["living_room"]
    values = sorted(living.values())

    assert len(set(values)) == 4, f"expected four distinct results, got {living}"
    assert values[0] < 120.0, "at least one apartment must fail the 2 hour threshold"
    assert values[-1] == pytest.approx(360.0), (
        "the top-floor unlit-side apartment should see the whole window, matching "
        "the unobstructed analytic case"
    )


# ---------------------------------------------------------------------------
# The site placement, and why it is read at all.
#
# Archicad's "Survey Point" IFC model position rotates the geometry through
# IfcSite's placement and then writes TrueNorth as (0,1), because the world
# coordinates it produces really are true-north-aligned. Its "Project Origin"
# option does the opposite. Both are correct; the analysis is unaffected
# either way because it reads world coordinates. Only a comparison against
# something *outside* the file -- a live Archicad -- needs to know which half
# of the pair carries the angle, and that is what site_rotation_deg is for.
# ---------------------------------------------------------------------------
def test_the_fixture_has_an_unrotated_site() -> None:
    """The default, and the case that keeps the cross-check arithmetic simple."""
    assert read_ifc(SAMPLE).site_rotation_deg == pytest.approx(0.0)


def _with_site_rotation(source: Path, destination: Path, degrees: float) -> Path:
    """The fixture, re-exported as though Archicad had rotated the site."""
    model = ifcopenshell.open(str(source))
    site = model.by_type("IfcSite")[0]
    radians = np.radians(degrees)
    site.ObjectPlacement.RelativePlacement.RefDirection = model.create_entity(
        "IfcDirection", DirectionRatios=(float(np.cos(radians)), float(np.sin(radians)), 0.0)
    )
    model.write(str(destination))
    return destination


def test_a_rotated_site_placement_is_read_back(tmp_path: Path) -> None:
    rotated = _with_site_rotation(SAMPLE, tmp_path / "rotated.ifc", 40.948)
    model = read_ifc(rotated)

    assert model.site_rotation_deg == pytest.approx(40.948, abs=1e-6)
    # TrueNorth is untouched, so the two are independent and both survive.
    assert model.true_north_bearing_deg % 360.0 == pytest.approx(30.0)


def test_the_site_rotation_does_not_reach_the_analysis(tmp_path: Path) -> None:
    """It is diagnostic metadata, not an input.

    ``SiteOrientation`` must keep taking its bearing from ``TrueNorth`` alone,
    because the geometry it is applied to is already in world coordinates with
    the site placement baked in. Adding the rotation here would count it twice.
    """
    rotated = _with_site_rotation(SAMPLE, tmp_path / "rotated.ifc", 40.948)
    orientation = read_ifc(rotated).orientation("Australia/Sydney")

    assert orientation.true_north_bearing_deg % 360.0 == pytest.approx(30.0)


def test_a_site_without_a_placement_reports_no_rotation(tmp_path: Path) -> None:
    """Absence must read as zero, not crash: it is the overwhelmingly common case."""
    model = ifcopenshell.open(str(SAMPLE))
    model.by_type("IfcSite")[0].ObjectPlacement = None
    stripped = tmp_path / "no_placement.ifc"
    model.write(str(stripped))

    assert read_ifc(stripped).site_rotation_deg == pytest.approx(0.0)


# ---------------------------------------------------------------------------
# Selecting living-room glazing by an ID suffix (D24), and zones by layer.
#
# The route for a practice that zones by *unit* rather than by room. There is
# then no living-room Zone to match a name against, and every window in the
# unit -- bedrooms, bathroom, kitchen -- would otherwise be counted as living
# room glazing. That does not fail; it returns an optimistically wrong number,
# which is the failure mode this project exists to avoid.
# ---------------------------------------------------------------------------
def _mark_openings(source: Path, destination: Path, suffix: str = "_L") -> Path:
    """The fixture, renamed to the ``_L`` convention, with one opening a door.

    Only the A-side openings are marked, so a test can tell selection from
    "everything matched". ``LongName`` is stripped from every space as well:
    with no room named "Living Room" anywhere, anything the scene finds must
    have come through the suffix.
    """
    model = ifcopenshell.open(str(source))

    for space in model.by_type("IfcSpace"):
        space.LongName = None

    windows = sorted(model.by_type("IfcWindow"), key=lambda w: w.Name)
    for window in windows:
        if "-A" in (window.Name or ""):
            window.Name = f"{window.Name}{suffix}"

    # Turn one marked window into a door in place. A balcony slider is a Door
    # in Archicad, and doors were 110 of 252 marked openings in the reference
    # project -- reading windows alone would drop nearly half the glazing.
    victim = next(w for w in windows if (w.Name or "").endswith(suffix))
    door = model.create_entity(
        "IfcDoor",
        GlobalId=victim.GlobalId,
        OwnerHistory=victim.OwnerHistory,
        Name=victim.Name,
        ObjectPlacement=victim.ObjectPlacement,
        Representation=victim.Representation,
        OverallHeight=victim.OverallHeight,
        OverallWidth=victim.OverallWidth,
    )
    for relation in model.by_type("IfcRelContainedInSpatialStructure"):
        relation.RelatedElements = tuple(
            door if e.id() == victim.id() else e for e in relation.RelatedElements
        )
    model.remove(victim)

    model.write(str(destination))
    return destination


def _suffix_scene(path: Path, **overrides: Any) -> Any:
    config = SceneConfig(timezone="Australia/Sydney", livable_opening_suffix="_L", **overrides)
    return build_scene(read_ifc(path), config)


def test_the_suffix_route_selects_only_the_marked_openings(tmp_path: Path) -> None:
    scene = _suffix_scene(_mark_openings(SAMPLE, tmp_path / "marked.ifc"))

    # Two A-side openings marked out of four; no space is named "Living Room".
    assert scene.provenance["windows_total"] == 2
    assert scene.provenance["windows_assessed"] == 2
    assert scene.provenance["living_rooms_matched"] == 2
    assert {a.space_name for a in scene.assignments} == {
        "Apartment L00-A",
        "Apartment L01-A",
    }


def test_a_marked_door_is_glazing_too(tmp_path: Path) -> None:
    """Half the reference project's living-room glazing was sliding doors."""
    marked = _mark_openings(SAMPLE, tmp_path / "marked.ifc")
    classes = {e.ifc_class for e in read_ifc(marked).elements if e.name.endswith("_L")}
    assert classes == {"IfcWindow", "IfcDoor"}, "the fixture must exercise both classes"

    scene = _suffix_scene(marked)
    assert scene.provenance["windows_assessed"] == 2, "the door must not be dropped"


def test_windows_only_would_miss_the_door(tmp_path: Path) -> None:
    """Guards the default in ``livable_opening_classes`` against being narrowed."""
    marked = _mark_openings(SAMPLE, tmp_path / "marked.ifc")
    scene = _suffix_scene(marked, livable_opening_classes=("IfcWindow",))

    assert scene.provenance["windows_assessed"] == 1


def test_the_suffix_must_be_a_suffix(tmp_path: Path) -> None:
    """``D06L`` and ``SD2.x_L`` coexisted in the reference project.

    Matching a bare trailing ``L`` would sweep up the first, which is a
    bathroom cavity slider and not living-room glazing at all.
    """
    marked = _mark_openings(SAMPLE, tmp_path / "marked.ifc", suffix="L")
    scene = _suffix_scene(marked)

    assert scene.provenance["windows_total"] == 0, (
        "openings ending in a bare 'L' must not match a '_L' convention"
    )


def test_the_suffix_route_ignores_room_names(tmp_path: Path) -> None:
    """The two routes are alternatives, not filters applied in series."""
    marked = _mark_openings(SAMPLE, tmp_path / "marked.ifc")
    scene = _suffix_scene(marked, living_room_space_names=("Nothing Matches This",))

    assert scene.provenance["windows_assessed"] == 2


def _put_on_layers(source: Path, destination: Path, assignment: dict[str, str]) -> Path:
    """The fixture, with named elements assigned to Archicad layers.

    ``IfcPresentationLayerAssignment`` points at representations rather than
    at products, which is how Archicad really writes it, so the fixture is
    built the same way round.
    """
    model = ifcopenshell.open(str(source))
    by_layer: dict[str, list[Any]] = {}
    for product in model.by_type("IfcProduct"):
        layer = assignment.get(product.Name or "")
        representation = getattr(product, "Representation", None)
        if layer is None or representation is None:
            continue
        by_layer.setdefault(layer, []).extend(representation.Representations)

    for layer, items in by_layer.items():
        model.create_entity(
            "IfcPresentationLayerAssignment", Name=layer, AssignedItems=tuple(items)
        )
    model.write(str(destination))
    return destination


def test_layers_are_read_back_onto_elements(tmp_path: Path) -> None:
    layered = _put_on_layers(
        SAMPLE, tmp_path / "layered.ifc", {"Apartment L00-A": "06 | Zone.SEPP 65"}
    )
    by_name = {e.name: e for e in read_ifc(layered).elements}

    assert by_name["Apartment L00-A"].layer == "06 | Zone.SEPP 65"
    assert by_name["Apartment L00-B"].layer == "", "an unassigned element has no layer"


def test_a_file_without_layers_reports_none(tmp_path: Path) -> None:
    """An IFC exported without layers must not look like one where all match."""
    assert all(element.layer == "" for element in read_ifc(SAMPLE).elements)


def test_apartment_zones_can_be_restricted_to_a_layer(tmp_path: Path) -> None:
    """The failure this prevents: a GFA zone counted as an apartment.

    A real project carries several kinds of Zone -- units, GFA, NLA, storage,
    a SEPP 65 duplicate set. Assessing all of them inflates the denominator of
    the compliance percentage, and nothing about the output looks wrong.
    """
    layered = _put_on_layers(
        SAMPLE,
        tmp_path / "layered.ifc",
        {
            "Apartment L00-A": "06 | Zone.SEPP 65",
            "Apartment L00-B": "06 | Zone.SEPP 65",
            "Apartment L01-A": "10 | Calc.GFA",
            "Apartment L01-B": "10 | Calc.GFA",
        },
    )
    scene = build_scene(
        read_ifc(layered),
        SceneConfig(
            timezone="Australia/Sydney",
            apartment_zone_layers=("06 | Zone.SEPP 65",),
        ),
    )

    assert scene.provenance["spaces_total"] == 2
    assert scene.provenance["living_rooms_matched"] == 2


def test_layer_matching_tolerates_spacing(tmp_path: Path) -> None:
    """A layer name retyped on a command line will not match byte for byte."""
    layered = _put_on_layers(
        SAMPLE, tmp_path / "layered.ifc", {"Apartment L00-A": "06 | Zone.SEPP 65"}
    )
    scene = build_scene(
        read_ifc(layered),
        SceneConfig(
            timezone="Australia/Sydney",
            apartment_zone_layers=("06  |  zone.sepp 65",),
        ),
    )
    assert scene.provenance["spaces_total"] == 1


def test_open_space_zones_are_never_apartments(tmp_path: Path) -> None:
    """A balcony Zone in the denominator would be an apartment with no windows.

    It would then read as an apartment receiving no living-room sunlight,
    which is a compliance failure invented out of a modelling convention.
    """
    layered = _put_on_layers(
        SAMPLE,
        tmp_path / "layered.ifc",
        {
            "Apartment L00-A": "06 | Zone.Units",
            "Apartment L00-B": "06 | Zone.Balcony",
        },
    )
    scene = build_scene(
        read_ifc(layered),
        SceneConfig(
            timezone="Australia/Sydney",
            living_room_space_names=(),
            apartment_zone_layers=("06 | Zone.Units",),
            open_space_zone_layers=("06 | Zone.Balcony",),
        ),
    )

    assert scene.provenance["spaces_total"] == 1

    # It went down the open-space route rather than being dropped. It does not
    # attach here because the fixture's two zones sit 10 m apart side by side,
    # not one above the other -- a balcony that far from its apartment is
    # correctly treated as communal. The attachment rule itself is covered by
    # the slab-based cases.
    assert scene.provenance["open_space_unattached"] == 1


def test_the_scene_description_states_which_routes_were_used() -> None:
    """These choices move the headline percentage, so they are always echoed."""
    described = SceneConfig(
        timezone="Australia/Sydney",
        livable_opening_suffix="_L",
        apartment_zone_layers=("06 | Zone.SEPP 65",),
        open_space_zone_layers=("06 | Zone.Balcony",),
    ).describe()

    assert "_L" in described
    assert "Window/Door" in described
    assert "06 | Zone.SEPP 65" in described
    assert "06 | Zone.Balcony" in described


def test_a_zone_is_gridded_on_its_floor_not_its_ceiling(model: Any) -> None:
    """The bug this guards against returns a plausible number from the wrong storey.

    A balcony slab is a solid and its walking surface is the top face. A
    balcony Zone is a void, and its top face is the underside of whatever is
    above -- gridding that would assess a plane one metre into the storey
    overhead, and nothing about the resulting hours would look wrong.
    """
    from sun_study.ingest.scene import _open_space_grid

    zone = model.of_class("IfcSpace")[0]
    lower, upper = zone.bounds
    config = SceneConfig(timezone="Australia/Sydney", open_space_height_m=1.0)

    samples = _open_space_grid(zone, zone.global_id, config)
    assert samples is not None

    heights = samples.positions[:, 2]
    assert heights.min() == pytest.approx(float(lower[2]) + 1.0, abs=1e-6)
    assert heights.max() == pytest.approx(float(lower[2]) + 1.0, abs=1e-6)
    assert float(upper[2]) - float(lower[2]) > 1.5, (
        "the fixture zone must be taller than the sample height for this to discriminate"
    )

    # Open space faces the sky whichever face it was derived from.
    assert np.allclose(samples.normals[:, 2], 1.0)


def test_a_slab_is_still_gridded_on_its_top(model: Any) -> None:
    from sun_study.ingest.scene import _open_space_grid

    slab = next(s for s in model.of_class("IfcSlab") if s.name.startswith("Balcony"))
    _, upper = slab.bounds
    config = SceneConfig(timezone="Australia/Sydney", open_space_height_m=1.0)

    samples = _open_space_grid(slab, slab.global_id, config)
    assert samples is not None
    assert samples.positions[:, 2].min() == pytest.approx(float(upper[2]) + 1.0, abs=1e-6)
    assert np.allclose(samples.normals[:, 2], 1.0)


def test_a_layer_that_matches_nothing_lists_what_is_there(tmp_path: Path) -> None:
    """A typo must not read as a building with no apartments.

    Layer names carry punctuation nobody reproduces from memory: the real
    project's '06 | Zone.Units' typed as '06|Zone.Units' matches nothing.
    Selecting zero zones silently would report 0 of 0 apartments compliant.
    """
    from sun_study.ingest.scene import SceneConfigError

    layered = _put_on_layers(
        SAMPLE, tmp_path / "layered.ifc", {"Apartment L00-A": "06 | Zone.Units"}
    )
    with pytest.raises(SceneConfigError) as caught:
        build_scene(
            read_ifc(layered),
            SceneConfig(timezone="Australia/Sydney", apartment_zone_layers=("06|Zone.Units",)),
        )

    message = str(caught.value)
    assert "06|Zone.Units" in message, "the message must repeat what was asked for"
    assert "06 | Zone.Units" in message, "and show the layer that is actually there"


def test_no_layer_filter_still_works_on_a_file_without_layers() -> None:
    """The overwhelmingly common case must not be made to fail."""
    scene = build_scene(read_ifc(SAMPLE), SceneConfig(timezone="Australia/Sydney"))
    assert scene.provenance["spaces_total"] == 4


def test_the_openings_per_apartment_spread_is_reported(tmp_path: Path) -> None:
    """The one line that says which criterion a run actually answers.

    A marker on living-room glazing gives most apartments one or two openings.
    A marker on every room requiring sunlight gives a two-bedroom apartment
    three or four. Pooling the second into an ADG 4A-1 figure lets an
    apartment pass on sun its living room never sees, and nothing in a
    compliance percentage shows the difference.
    """
    scene = _suffix_scene(_mark_openings(SAMPLE, tmp_path / "marked.ifc"))

    # The fixture marks one opening in each of two apartments.
    assert scene.provenance["openings_per_apartment"] == {1: 2}
    assert "openings per apartment: 1x2 (mean 1.00 across 2 apartments)" in scene.describe()


def test_apartments_with_no_openings_are_not_counted_in_the_spread() -> None:
    """A mean dragged down by unglazed spaces would misread the convention."""
    scene = build_scene(
        read_ifc(SAMPLE),
        SceneConfig(timezone="Australia/Sydney", living_room_space_names=()),
    )
    histogram = scene.provenance["openings_per_apartment"]
    assert isinstance(histogram, dict)
    assert 0 not in histogram
