"""IFC ingest: units, north, georeferencing and window-to-space containment.

Milestone M2's acceptance criterion is that the fixture loads with correct
north, units and containment, so those three get the most attention here.

The fixture is generated by ``tests/fixtures/make_sample_building.py`` and is
deliberately awkward: millimetre units, true north 30 degrees off project
north, and one window with no space boundary.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import ifcopenshell
import numpy as np
import pytest

from sun_study.core.orientation import SiteOrientation
from sun_study.ingest.ifc import GeoreferencingError, read_ifc
from sun_study.ingest.scene import SceneConfig, build_scene, planar_face_grid

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"
SAMPLE = FIXTURES / "sample_building.ifc"

# Values the fixture generator declares. If these drift apart the fixture has
# been regenerated with different inputs and the golden results are stale.
EXPECTED_LATITUDE = -33.75
EXPECTED_LONGITUDE = 151.25
EXPECTED_ELEVATION_M = 20.0
EXPECTED_NORTH_BEARING = 30.0
EXPECTED_UNIT_SCALE = 0.001


@pytest.fixture(scope="module")
def model() -> Any:
    return read_ifc(SAMPLE)


def test_fixture_is_committed() -> None:
    """The fixture is synthetic and committed on purpose (brief section 10)."""
    assert SAMPLE.is_file(), (
        f"{SAMPLE} is missing; regenerate with "
        f"'uv run python tests/fixtures/make_sample_building.py'"
    )


def test_committed_fixture_matches_its_generator(tmp_path: Path) -> None:
    """The .ifc must be exactly what the script produces, byte for byte.

    Catches two things that would otherwise be invisible: the committed file
    having been hand-edited, and the generator having changed without the
    fixture and its golden results being regenerated.

    This is only possible because generation is deterministic -- GUIDs come
    from a counter and the SPF header timestamp is pinned, since IfcOpenShell
    otherwise stamps the current time and every regeneration would be a diff.
    """
    import subprocess
    import sys

    script = FIXTURES / "make_sample_building.py"
    regenerated = tmp_path / "sample_building.ifc"

    source = script.read_text(encoding="utf-8").replace(
        'destination = Path(__file__).parent / "sample_building.ifc"',
        f"destination = Path({str(regenerated)!r})",
    )
    relocated = tmp_path / "generator.py"
    relocated.write_text(source, encoding="utf-8")

    subprocess.run([sys.executable, str(relocated)], check=True, capture_output=True)

    assert regenerated.read_bytes() == SAMPLE.read_bytes(), (
        "the committed fixture differs from what its generator produces; "
        "re-run 'uv run python tests/fixtures/make_sample_building.py' and "
        "regenerate the golden file with SUN_STUDY_UPDATE_GOLDEN=1"
    )


# ---------------------------------------------------------------------------
# Units -- the two scales that must not be conflated.
# ---------------------------------------------------------------------------
def test_declared_unit_is_millimetres(model: Any) -> None:
    assert model.length_unit_scale == pytest.approx(EXPECTED_UNIT_SCALE)


def test_geometry_arrives_in_metres_not_project_units(model: Any) -> None:
    """The iterator already applies the unit scale; applying it again would
    shrink a 2.4 m window to 2.4 mm."""
    windows = model.of_class("IfcWindow")
    assert len(windows) == 4

    lower, upper = windows[0].bounds
    width = float(np.max(upper - lower))
    assert width == pytest.approx(2.4, abs=1e-6), (
        f"window measures {width} across; expected 2.4 m. A value near 2400 means "
        f"the geometry is still in millimetres, and one near 0.0024 means the unit "
        f"scale has been applied twice."
    )


def test_building_extent_is_plausible_in_metres(model: Any) -> None:
    mesh = model.occluder_mesh()
    extent = mesh.vertices.max(axis=0) - mesh.vertices.min(axis=0)
    assert 20.0 < float(extent[0]) < 100.0, f"building spans {extent[0]} m across"
    assert 5.0 < float(extent[2]) < 30.0, f"building is {extent[2]} m tall"


def test_site_elevation_is_converted_from_project_units(model: Any) -> None:
    """RefElevation is an attribute, so unlike geometry it *does* need scaling.

    The fixture stores 20000 (millimetres). Reading it unscaled would place the
    site 20 km up; scaling geometry as well would put it at 20 mm.
    """
    assert model.site_elevation_m == pytest.approx(EXPECTED_ELEVATION_M)


# ---------------------------------------------------------------------------
# North and georeferencing.
# ---------------------------------------------------------------------------
def test_true_north_bearing_is_read(model: Any) -> None:
    assert model.true_north_bearing_deg == pytest.approx(EXPECTED_NORTH_BEARING, abs=1e-9)


def test_geolocation_is_read(model: Any) -> None:
    assert model.latitude_deg == pytest.approx(EXPECTED_LATITUDE)
    assert model.longitude_deg == pytest.approx(EXPECTED_LONGITUDE)


def test_orientation_requires_an_explicit_timezone(model: Any) -> None:
    """Decision D3. IFC has no IANA zone, and none is invented."""
    orientation = model.orientation("Australia/Sydney")
    assert isinstance(orientation, SiteOrientation)
    assert orientation.timezone == "Australia/Sydney"

    with pytest.raises(ValueError, match="timezone"):
        model.orientation("")


def test_describe_echoes_what_a_human_must_check(model: Any) -> None:
    line = model.describe("Australia/Sydney")
    assert "33.750000S" in line
    assert "151.250000E" in line
    assert "30.000" in line
    assert "Australia/Sydney" in line
    assert "0.001" in line


# ---------------------------------------------------------------------------
# Failing loudly. Every one of these silently rotates or relocates results.
# ---------------------------------------------------------------------------
def _strip_and_write(destination: Path, mutate: Any) -> Path:
    file = ifcopenshell.open(str(SAMPLE))
    mutate(file)
    file.write(str(destination))
    return destination


def test_missing_true_north_raises(tmp_path: Path) -> None:
    def remove_north(file: Any) -> None:
        for context in file.by_type("IfcGeometricRepresentationContext", include_subtypes=False):
            context.TrueNorth = None

    path = _strip_and_write(tmp_path / "no_north.ifc", remove_north)
    with pytest.raises(GeoreferencingError, match="North Direction"):
        read_ifc(path)


def test_missing_latitude_raises(tmp_path: Path) -> None:
    def remove_location(file: Any) -> None:
        for site in file.by_type("IfcSite"):
            site.RefLatitude = None
            site.RefLongitude = None

    path = _strip_and_write(tmp_path / "no_location.ifc", remove_location)
    with pytest.raises(GeoreferencingError, match="Project Location"):
        read_ifc(path)


def test_ambiguous_multiple_located_sites_raises(tmp_path: Path) -> None:
    """Two georeferenced sites means the tool cannot know which one governs."""

    def duplicate_site(file: Any) -> None:
        original = file.by_type("IfcSite")[0]
        file.create_entity(
            "IfcSite",
            GlobalId=ifcopenshell.guid.new(),
            Name="Second Site",
            RefLatitude=original.RefLatitude,
            RefLongitude=original.RefLongitude,
            RefElevation=original.RefElevation,
        )

    path = _strip_and_write(tmp_path / "two_sites.ifc", duplicate_site)
    with pytest.raises(GeoreferencingError, match="ambiguous"):
        read_ifc(path)


def test_missing_file_raises() -> None:
    with pytest.raises(FileNotFoundError):
        read_ifc(FIXTURES / "does_not_exist.ifc")


def test_ifcopenshell_helper_would_have_defaulted_silently() -> None:
    """Why this module does not use ``get_true_north`` for the presence check.

    The helper returns 0 for a file with no TrueNorth, which is indistinguishable
    from a project genuinely aligned to true north. That is the silent default
    the brief forbids, so this pins the behaviour we are deliberately avoiding.
    """
    import ifcopenshell.util.geolocation

    file = ifcopenshell.open(str(SAMPLE))
    for context in file.by_type("IfcGeometricRepresentationContext", include_subtypes=False):
        context.TrueNorth = None

    assert ifcopenshell.util.geolocation.get_true_north(file) == 0


# ---------------------------------------------------------------------------
# Containment -- which space does each window serve.
# ---------------------------------------------------------------------------
@pytest.fixture(scope="module")
def scene(model: Any) -> Any:
    return build_scene(model, SceneConfig(timezone="Australia/Sydney"))


def test_every_window_resolves_to_the_right_apartment(scene: Any) -> None:
    resolved = {a.window_name: a.space_name for a in scene.assignments}
    assert resolved == {
        "Window L00-A": "Apartment L00-A",
        "Window L00-B": "Apartment L00-B",
        "Window L01-A": "Apartment L01-A",
        "Window L01-B": "Apartment L01-B",
    }


def test_both_resolution_routes_are_exercised_and_reported(scene: Any) -> None:
    """The fixture omits one space boundary precisely to reach the fallback."""
    methods = {a.window_name: a.method for a in scene.assignments}
    assert methods["Window L00-A"] == "geometric"
    assert methods["Window L00-B"] == "space-boundary"

    assert scene.provenance["resolved_by_space_boundary"] == 3
    assert scene.provenance["resolved_geometrically"] == 1
    assert scene.provenance["unresolved"] == 0


def test_a_window_far_from_any_space_is_left_unresolved(model: Any) -> None:
    """Guessing would attach a stairwell window to whichever room is nearest."""
    from sun_study.ingest.scene import _assign_windows

    windows = model.of_class("IfcWindow")
    assignments = _assign_windows(model, windows, ())
    assert all(a.method == "unresolved" for a in assignments)
    assert all(a.space_id is None for a in assignments)


def test_living_rooms_are_matched_on_long_name(model: Any) -> None:
    """Archicad puts the Zone category in LongName and the apartment id in Name.

    Matching only Name finds nothing, which reads as a building with no living
    rooms rather than as a configuration error. See decision D6.
    """
    spaces = model.of_class("IfcSpace")
    assert all(space.long_name == "Living Room" for space in spaces)
    assert all(space.name.startswith("Apartment") for space in spaces)

    scene = build_scene(model, SceneConfig(timezone="Australia/Sydney"))
    assert scene.provenance["living_rooms_matched"] == 4
    assert scene.provenance["windows_assessed"] == 4


def test_a_non_matching_room_name_assesses_nothing(model: Any) -> None:
    """The failure mode above, made visible rather than silent."""
    scene = build_scene(
        model, SceneConfig(timezone="Australia/Sydney", living_room_space_names=("Kitchen",))
    )
    assert scene.provenance["living_rooms_matched"] == 0
    assert scene.provenance["windows_assessed"] == 0
    assert len(scene.window_samples) == 0


def test_empty_room_filter_assesses_every_space(model: Any) -> None:
    scene = build_scene(model, SceneConfig(timezone="Australia/Sydney", living_room_space_names=()))
    assert scene.provenance["living_rooms_matched"] == 4


# ---------------------------------------------------------------------------
# Sampling on real IFC geometry.
# ---------------------------------------------------------------------------
def test_window_samples_face_outward_and_clear_the_facade(model: Any, scene: Any) -> None:
    """Samples must sit outside the wall, or the facade shades its own windows."""
    samples = scene.window_samples
    assert len(samples) > 0

    # Every window in the fixture faces project +Y.
    np.testing.assert_allclose(samples.normals[:, 1], 1.0, atol=1e-9)

    walls = model.of_class("IfcWall")
    facade_y = max(float(wall.bounds[1][1]) for wall in walls)
    assert float(samples.positions[:, 1].min()) > facade_y, (
        "window samples must lie outside the outermost wall face"
    )


def test_window_sample_count_matches_the_grid(scene: Any) -> None:
    """A 2.4 x 1.8 m window at 200 mm is 12 x 9 = 108 samples, four windows."""
    assert len(scene.window_samples) == 4 * 12 * 9


def test_open_space_samples_face_up_and_sit_above_the_slab(scene: Any) -> None:
    samples = scene.open_space_samples
    assert len(samples) > 0
    np.testing.assert_allclose(samples.normals, np.tile([0.0, 0.0, 1.0], (len(samples), 1)))


def test_planar_face_grid_follows_a_rotated_window() -> None:
    """The in-plane basis is derived from the face, not assumed axis-aligned."""
    from sun_study.core.geometry import box, rotation_about_z

    angle = 37.0
    mesh = box((-1.2, -0.1, 0.0), (1.2, 0.1, 1.8)).rotated_about_z(angle)

    # The panel's outward face is -Y before rotation, so the expected normal is
    # that axis carried through the same rotation. Deriving it from the matrix
    # rather than by hand keeps the test honest about the sign convention.
    expected_normal = rotation_about_z(angle) @ np.array([0.0, -1.0, 0.0])

    samples = planar_face_grid(mesh, "w", expected_normal, spacing_m=0.2, surface_offset_m=0.05)
    assert samples is not None
    # A 2.4 x 1.8 m panel at 200 mm spacing.
    assert len(samples) == 12 * 9

    np.testing.assert_allclose(
        samples.normals, np.tile(expected_normal, (len(samples), 1)), atol=1e-12
    )
    np.testing.assert_allclose(samples.normals[:, 2], 0.0, atol=1e-12)

    # And the samples stand off the rotated face by exactly the offset.
    face_centre = rotation_about_z(angle) @ np.array([0.0, -0.1, 0.9])
    assert float((samples.positions.mean(axis=0) - face_centre) @ expected_normal) == pytest.approx(
        0.05, abs=1e-9
    )


def test_planar_face_grid_picks_the_face_the_hint_points_at() -> None:
    """The two big faces of a window panel differ only in sign, so the hint
    decides which one is glazed-side-out. Getting it wrong puts every sample
    inside the room."""
    from sun_study.core.geometry import box

    mesh = box((-1.2, -0.1, 0.0), (1.2, 0.1, 1.8))
    for hint in ([0.0, 1.0, 0.0], [0.0, -1.0, 0.0]):
        samples = planar_face_grid(mesh, "w", np.array(hint), spacing_m=0.4)
        assert samples is not None
        np.testing.assert_allclose(samples.normals[0], hint, atol=1e-12)


def test_planar_face_grid_returns_none_for_empty_geometry() -> None:
    from sun_study.core.geometry import TriangleMesh

    assert planar_face_grid(TriangleMesh.empty(), "w", np.array([0.0, 1.0, 0.0])) is None


def test_spaces_are_not_occluders(model: Any) -> None:
    """A Zone is a void; treating it as solid shades every apartment completely."""
    with_spaces = model.occluder_mesh(include_spaces=True).triangle_count
    without = model.occluder_mesh().triangle_count
    assert without < with_spaces
    assert without == sum(
        e.mesh.triangle_count for e in model.elements if e.ifc_class != "IfcSpace"
    )


def test_context_radius_drops_distant_occluders(model: Any) -> None:
    """D9. The cutoff is measured from the analysed spaces, not the file origin."""
    unlimited = build_scene(model, SceneConfig(timezone="Australia/Sydney"))
    clipped = build_scene(model, SceneConfig(timezone="Australia/Sydney", context_radius_m=15.0))
    assert clipped.occluders.triangle_count < unlimited.occluders.triangle_count


def test_provenance_records_the_assumptions(scene: Any) -> None:
    """A result separated from its assumptions cannot be reproduced or argued with."""
    for key in (
        "source",
        "schema",
        "length_unit_scale",
        "true_north_bearing_deg",
        "windows_assessed",
        "resolved_by_space_boundary",
        "resolved_geometrically",
        "unresolved",
        "vegetation_included",
    ):
        assert key in scene.provenance, f"provenance is missing {key}"

    assert scene.provenance["vegetation_included"] is False
    assert "vegetation excluded" in scene.config.describe()
    assert "context radius unlimited" in scene.config.describe()


# ---------------------------------------------------------------------------
# Golden results -- fail CI on drift (brief section 7).
# ---------------------------------------------------------------------------
GOLDEN = FIXTURES / "golden_sample_building.json"


def run_fixture_pipeline() -> dict[str, dict[str, float]]:
    """The whole chain on the fixture, reduced to per-apartment minutes."""
    import datetime as dt

    from sun_study.core.analysis import summarise_by_parent, sunlit_matrix
    from sun_study.core.occlusion import Occluder
    from sun_study.core.solar import assessment_times, solar_position

    model = read_ifc(SAMPLE)
    scene = build_scene(model, SceneConfig(timezone="Australia/Sydney"))

    times = assessment_times(
        dt.date(2024, 6, 21), "Australia/Sydney", dt.time(9, 0), dt.time(15, 0), 10
    )
    suns = scene.orientation.sun_vectors(
        solar_position(times, model.latitude_deg, model.longitude_deg)
    )
    occluder = Occluder(scene.occluders)
    names = {e.global_id: e.name for e in model.elements}

    results: dict[str, dict[str, float]] = {}
    for label, points in (
        ("living_room", scene.window_samples),
        ("open_space", scene.open_space_samples),
    ):
        summary = summarise_by_parent(points, sunlit_matrix(points, occluder, suns), 10.0)
        results[label] = {
            names.get(pid, pid): round(float(minutes), 3)
            for pid, minutes in zip(summary.parent_ids, summary.cumulative_minutes, strict=True)
        }
    return results


def test_fixture_results_match_the_golden_file() -> None:
    """Regenerate deliberately with SUN_STUDY_UPDATE_GOLDEN=1, never casually.

    A change here means the numbers this tool reports for a known building have
    moved. That is either a fix or a regression, and it should never pass
    unnoticed.
    """
    actual = run_fixture_pipeline()

    if os.environ.get("SUN_STUDY_UPDATE_GOLDEN") == "1":
        GOLDEN.write_text(json.dumps(actual, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    assert GOLDEN.is_file(), (
        f"{GOLDEN} is missing; create it with SUN_STUDY_UPDATE_GOLDEN=1 uv run pytest"
    )
    expected = json.loads(GOLDEN.read_text(encoding="utf-8"))

    assert actual.keys() == expected.keys()
    for section, values in expected.items():
        assert actual[section].keys() == values.keys(), f"{section} apartments changed"
        for name, minutes in values.items():
            assert actual[section][name] == pytest.approx(minutes, abs=1e-3), (
                f"{section} / {name}: {actual[section][name]} minutes, golden says {minutes}"
            )


def test_the_fixture_discriminates() -> None:
    """A golden file of four identical numbers would catch almost nothing.

    The fixture is built so the two storeys and the two sides all differ: the
    context block bites into the lower storey and the A side, and the balcony
    one level up overhangs each window. If these collapse together the fixture
    has stopped testing anything.
    """
    living = run_fixture_pipeline()["living_room"]
    values = sorted(living.values())

    assert len(set(values)) == 4, f"expected four distinct results, got {living}"
    assert values[0] < 120.0, "at least one apartment must fail the 2 hour threshold"
    assert values[-1] == pytest.approx(360.0), (
        "the top-floor unlit-side apartment should see the whole window, matching "
        "the unobstructed analytic case"
    )
